### ISSUE TITLE
It would be nice to see more of Ellie

### ISSUE THREAD

**Issue by diraneyya** [WildCodeSchool/2023-01-EN-Berlin-Remote2-Markdown#19]
https://github.com/WildCodeSchool/2023-01-EN-Berlin-Remote2-Markdown/blob/e88cf587dd5415163ff39e4aee0a087ed4faa0b2/lisa-roehrig-new.md?plain=1#L15

**Comment by ghost** [comment]
I don't understand your request. There is no possible cuter Photo than this :-)
